DEPENDENT_LIBRARIES_PATH := blacksiren/libbsiren/libs/$(TARGET_ARCH_ABI)

include $(CLEAR_VARS)
LOCAL_MODULE := libbsiren
LOCAL_SRC_FILES := $(DEPENDENT_LIBRARIES_PATH)/libbsiren.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libr2mvdrbf
LOCAL_SRC_FILES := $(DEPENDENT_LIBRARIES_PATH)/libr2mvdrbf.so
#include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libr2ssp
LOCAL_SRC_FILES := $(DEPENDENT_LIBRARIES_PATH)/libr2ssp.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libztvad
LOCAL_SRC_FILES := $(DEPENDENT_LIBRARIES_PATH)/libztvad.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libr2vt
LOCAL_SRC_FILES := $(DEPENDENT_LIBRARIES_PATH)/libr2vt.so
include $(PREBUILT_SHARED_LIBRARY)
