# Copyright (C) 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

crypto_sources := \
  $(MY_LOCAL_PATH)/android_compat_hacks.c \
  $(MY_LOCAL_PATH)/android_compat_keywrap.c \
  $(MY_LOCAL_PATH)/err_data.c \
  $(MY_LOCAL_PATH)/src/crypto/aes/aes.c \
  $(MY_LOCAL_PATH)/src/crypto/aes/mode_wrappers.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_bitstr.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_bool.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_bytes.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_d2i_fp.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_dup.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_enum.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_gentm.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_i2d_fp.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_int.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_mbstr.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_object.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_octet.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_print.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_strnid.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_time.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_type.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_utctm.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/a_utf8.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/asn1_lib.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/asn1_par.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/asn_pack.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/bio_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/bio_ndef.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/f_enum.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/f_int.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/f_string.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/t_bitst.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/t_pkey.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/tasn_dec.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/tasn_enc.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/tasn_fre.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/tasn_new.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/tasn_prn.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/tasn_typ.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/tasn_utl.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/x_bignum.c \
  $(MY_LOCAL_PATH)/src/crypto/asn1/x_long.c \
  $(MY_LOCAL_PATH)/src/crypto/base64/base64.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/bio.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/bio_mem.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/buffer.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/connect.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/fd.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/file.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/hexdump.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/pair.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/printf.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/socket.c \
  $(MY_LOCAL_PATH)/src/crypto/bio/socket_helper.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/add.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/asm/x86_64-gcc.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/bn.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/cmp.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/convert.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/ctx.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/div.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/exponentiation.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/gcd.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/generic.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/kronecker.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/montgomery.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/mul.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/prime.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/random.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/rsaz_exp.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/shift.c \
  $(MY_LOCAL_PATH)/src/crypto/bn/sqrt.c \
  $(MY_LOCAL_PATH)/src/crypto/buf/buf.c \
  $(MY_LOCAL_PATH)/src/crypto/bytestring/ber.c \
  $(MY_LOCAL_PATH)/src/crypto/bytestring/cbb.c \
  $(MY_LOCAL_PATH)/src/crypto/bytestring/cbs.c \
  $(MY_LOCAL_PATH)/src/crypto/chacha/chacha_generic.c \
  $(MY_LOCAL_PATH)/src/crypto/chacha/chacha_vec.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/aead.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/cipher.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/derive_key.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_aes.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_chacha20poly1305.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_des.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_null.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_rc2.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_rc4.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_ssl3.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/e_tls.c \
  $(MY_LOCAL_PATH)/src/crypto/cipher/tls_cbc.c \
  $(MY_LOCAL_PATH)/src/crypto/cmac/cmac.c \
  $(MY_LOCAL_PATH)/src/crypto/conf/conf.c \
  $(MY_LOCAL_PATH)/src/crypto/cpu-arm.c \
  $(MY_LOCAL_PATH)/src/crypto/cpu-intel.c \
  $(MY_LOCAL_PATH)/src/crypto/crypto.c \
  $(MY_LOCAL_PATH)/src/crypto/des/des.c \
  $(MY_LOCAL_PATH)/src/crypto/dh/check.c \
  $(MY_LOCAL_PATH)/src/crypto/dh/dh.c \
  $(MY_LOCAL_PATH)/src/crypto/dh/dh_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/dh/dh_impl.c \
  $(MY_LOCAL_PATH)/src/crypto/dh/params.c \
  $(MY_LOCAL_PATH)/src/crypto/digest/digest.c \
  $(MY_LOCAL_PATH)/src/crypto/digest/digests.c \
  $(MY_LOCAL_PATH)/src/crypto/directory_posix.c \
  $(MY_LOCAL_PATH)/src/crypto/directory_win.c \
  $(MY_LOCAL_PATH)/src/crypto/dsa/dsa.c \
  $(MY_LOCAL_PATH)/src/crypto/dsa/dsa_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/dsa/dsa_impl.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/ec.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/ec_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/ec_key.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/ec_montgomery.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/oct.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/p256-64.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/simple.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/util-64.c \
  $(MY_LOCAL_PATH)/src/crypto/ec/wnaf.c \
  $(MY_LOCAL_PATH)/src/crypto/ecdh/ecdh.c \
  $(MY_LOCAL_PATH)/src/crypto/ecdsa/ecdsa.c \
  $(MY_LOCAL_PATH)/src/crypto/ecdsa/ecdsa_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/engine/engine.c \
  $(MY_LOCAL_PATH)/src/crypto/err/err.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/algorithm.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/digestsign.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/evp.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/evp_ctx.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/p_dsa_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/p_ec.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/p_ec_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/p_hmac.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/p_hmac_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/p_rsa.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/p_rsa_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/pbkdf.c \
  $(MY_LOCAL_PATH)/src/crypto/evp/sign.c \
  $(MY_LOCAL_PATH)/src/crypto/ex_data.c \
  $(MY_LOCAL_PATH)/src/crypto/hkdf/hkdf.c \
  $(MY_LOCAL_PATH)/src/crypto/hmac/hmac.c \
  $(MY_LOCAL_PATH)/src/crypto/lhash/lhash.c \
  $(MY_LOCAL_PATH)/src/crypto/md4/md4.c \
  $(MY_LOCAL_PATH)/src/crypto/md5/md5.c \
  $(MY_LOCAL_PATH)/src/crypto/mem.c \
  $(MY_LOCAL_PATH)/src/crypto/modes/cbc.c \
  $(MY_LOCAL_PATH)/src/crypto/modes/cfb.c \
  $(MY_LOCAL_PATH)/src/crypto/modes/ctr.c \
  $(MY_LOCAL_PATH)/src/crypto/modes/gcm.c \
  $(MY_LOCAL_PATH)/src/crypto/modes/ofb.c \
  $(MY_LOCAL_PATH)/src/crypto/obj/obj.c \
  $(MY_LOCAL_PATH)/src/crypto/obj/obj_xref.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_all.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_info.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_lib.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_oth.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_pk8.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_pkey.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_x509.c \
  $(MY_LOCAL_PATH)/src/crypto/pem/pem_xaux.c \
  $(MY_LOCAL_PATH)/src/crypto/pkcs8/p5_pbe.c \
  $(MY_LOCAL_PATH)/src/crypto/pkcs8/p5_pbev2.c \
  $(MY_LOCAL_PATH)/src/crypto/pkcs8/p8_pkey.c \
  $(MY_LOCAL_PATH)/src/crypto/pkcs8/pkcs8.c \
  $(MY_LOCAL_PATH)/src/crypto/poly1305/poly1305.c \
  $(MY_LOCAL_PATH)/src/crypto/poly1305/poly1305_arm.c \
  $(MY_LOCAL_PATH)/src/crypto/poly1305/poly1305_vec.c \
  $(MY_LOCAL_PATH)/src/crypto/rand/hwrand.c \
  $(MY_LOCAL_PATH)/src/crypto/rand/rand.c \
  $(MY_LOCAL_PATH)/src/crypto/rand/urandom.c \
  $(MY_LOCAL_PATH)/src/crypto/rand/windows.c \
  $(MY_LOCAL_PATH)/src/crypto/rc4/rc4.c \
  $(MY_LOCAL_PATH)/src/crypto/refcount_c11.c \
  $(MY_LOCAL_PATH)/src/crypto/refcount_lock.c \
  $(MY_LOCAL_PATH)/src/crypto/rsa/blinding.c \
  $(MY_LOCAL_PATH)/src/crypto/rsa/padding.c \
  $(MY_LOCAL_PATH)/src/crypto/rsa/rsa.c \
  $(MY_LOCAL_PATH)/src/crypto/rsa/rsa_asn1.c \
  $(MY_LOCAL_PATH)/src/crypto/rsa/rsa_impl.c \
  $(MY_LOCAL_PATH)/src/crypto/sha/sha1.c \
  $(MY_LOCAL_PATH)/src/crypto/sha/sha256.c \
  $(MY_LOCAL_PATH)/src/crypto/sha/sha512.c \
  $(MY_LOCAL_PATH)/src/crypto/stack/stack.c \
  $(MY_LOCAL_PATH)/src/crypto/thread.c \
  $(MY_LOCAL_PATH)/src/crypto/thread_none.c \
  $(MY_LOCAL_PATH)/src/crypto/thread_pthread.c \
  $(MY_LOCAL_PATH)/src/crypto/thread_win.c \
  $(MY_LOCAL_PATH)/src/crypto/time_support.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/a_digest.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/a_sign.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/a_strex.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/a_verify.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/asn1_gen.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/by_dir.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/by_file.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/i2d_pr.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/pkcs7.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/t_crl.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/t_x509.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/t_x509a.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_att.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_cmp.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_d2.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_def.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_ext.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_lu.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_obj.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_r2x.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_req.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_set.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_trs.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_txt.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_v3.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_vfy.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509_vpm.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509cset.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509name.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509rset.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509spki.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x509type.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_algor.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_all.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_attrib.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_crl.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_exten.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_info.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_name.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_pkey.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_pubkey.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_req.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_sig.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_spki.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_val.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_x509.c \
  $(MY_LOCAL_PATH)/src/crypto/x509/x_x509a.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/pcy_cache.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/pcy_data.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/pcy_lib.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/pcy_map.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/pcy_node.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/pcy_tree.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_akey.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_akeya.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_alt.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_bcons.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_bitst.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_conf.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_cpols.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_crld.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_enum.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_extku.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_genn.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_ia5.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_info.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_int.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_lib.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_ncons.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_pci.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_pcia.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_pcons.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_pku.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_pmaps.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_prn.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_purp.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_skey.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_sxnet.c \
  $(MY_LOCAL_PATH)/src/crypto/x509v3/v3_utl.c \

ssl_sources := \
  $(MY_LOCAL_PATH)/src/ssl/d1_both.c \
  $(MY_LOCAL_PATH)/src/ssl/d1_clnt.c \
  $(MY_LOCAL_PATH)/src/ssl/d1_lib.c \
  $(MY_LOCAL_PATH)/src/ssl/d1_meth.c \
  $(MY_LOCAL_PATH)/src/ssl/d1_pkt.c \
  $(MY_LOCAL_PATH)/src/ssl/d1_srtp.c \
  $(MY_LOCAL_PATH)/src/ssl/d1_srvr.c \
  $(MY_LOCAL_PATH)/src/ssl/pqueue/pqueue.c \
  $(MY_LOCAL_PATH)/src/ssl/s3_both.c \
  $(MY_LOCAL_PATH)/src/ssl/s3_clnt.c \
  $(MY_LOCAL_PATH)/src/ssl/s3_enc.c \
  $(MY_LOCAL_PATH)/src/ssl/s3_lib.c \
  $(MY_LOCAL_PATH)/src/ssl/s3_meth.c \
  $(MY_LOCAL_PATH)/src/ssl/s3_pkt.c \
  $(MY_LOCAL_PATH)/src/ssl/s3_srvr.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_aead_ctx.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_algs.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_asn1.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_cert.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_cipher.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_lib.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_rsa.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_sess.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_stat.c \
  $(MY_LOCAL_PATH)/src/ssl/ssl_txt.c \
  $(MY_LOCAL_PATH)/src/ssl/t1_enc.c \
  $(MY_LOCAL_PATH)/src/ssl/t1_lib.c \
  $(MY_LOCAL_PATH)/src/ssl/t1_reneg.c \

linux_aarch64_sources := \
  $(MY_LOCAL_PATH)/linux-aarch64/crypto/aes/aesv8-armx.S \
  $(MY_LOCAL_PATH)/linux-aarch64/crypto/modes/ghashv8-armx.S \
  $(MY_LOCAL_PATH)/linux-aarch64/crypto/sha/sha1-armv8.S \
  $(MY_LOCAL_PATH)/linux-aarch64/crypto/sha/sha256-armv8.S \
  $(MY_LOCAL_PATH)/linux-aarch64/crypto/sha/sha512-armv8.S \

linux_arm_sources := \
  $(MY_LOCAL_PATH)/linux-arm/crypto/aes/aes-armv4.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/aes/aesv8-armx.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/aes/bsaes-armv7.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/bn/armv4-mont.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/modes/ghash-armv4.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/modes/ghashv8-armx.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/sha/sha1-armv4-large.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/sha/sha256-armv4.S \
  $(MY_LOCAL_PATH)/linux-arm/crypto/sha/sha512-armv4.S \
  $(MY_LOCAL_PATH)/src/crypto/chacha/chacha_vec_arm.S \
  $(MY_LOCAL_PATH)/src/crypto/cpu-arm-asm.S \
  $(MY_LOCAL_PATH)/src/crypto/poly1305/poly1305_arm_asm.S \

linux_x86_sources := \
  $(MY_LOCAL_PATH)/linux-x86/crypto/aes/aes-586.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/aes/aesni-x86.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/aes/vpaes-x86.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/bn/bn-586.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/bn/co-586.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/bn/x86-mont.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/cpu-x86-asm.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/md5/md5-586.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/modes/ghash-x86.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/rc4/rc4-586.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/sha/sha1-586.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/sha/sha256-586.S \
  $(MY_LOCAL_PATH)/linux-x86/crypto/sha/sha512-586.S \

linux_x86_64_sources := \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/aes/aes-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/aes/aesni-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/aes/bsaes-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/aes/vpaes-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/bn/rsaz-avx2.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/bn/rsaz-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/bn/x86_64-mont.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/bn/x86_64-mont5.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/cpu-x86_64-asm.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/md5/md5-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/modes/aesni-gcm-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/modes/ghash-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/rand/rdrand-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/rc4/rc4-md5-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/rc4/rc4-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/sha/sha1-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/sha/sha256-x86_64.S \
  $(MY_LOCAL_PATH)/linux-x86_64/crypto/sha/sha512-x86_64.S \

mac_x86_sources := \
  $(MY_LOCAL_PATH)/mic-x86/crypto/aes/aes-586.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/aes/aesni-x86.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/aes/vpaes-x86.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/bn/bn-586.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/bn/co-586.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/bn/x86-mont.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/cpu-x86-asm.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/md5/md5-586.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/modes/ghash-x86.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/rc4/rc4-586.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/sha/sha1-586.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/sha/sha256-586.S \
  $(MY_LOCAL_PATH)/mic-x86/crypto/sha/sha512-586.S \

mac_x86_64_sources := \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/aes/aes-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/aes/aesni-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/aes/bsaes-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/aes/vpaes-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/bn/rsaz-avx2.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/bn/rsaz-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/bn/x86_64-mont.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/bn/x86_64-mont5.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/cpu-x86_64-asm.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/md5/md5-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/modes/aesni-gcm-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/modes/ghash-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/rand/rdrand-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/rc4/rc4-md5-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/rc4/rc4-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/sha/sha1-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/sha/sha256-x86_64.S \
  $(MY_LOCAL_PATH)/mic-x86_64/crypto/sha/sha512-x86_64.S \

win_x86_sources := \
  $(MY_LOCAL_PATH)/win-x86/crypto/aes/aes-586.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/aes/aesni-x86.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/aes/vpaes-x86.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/bn/bn-586.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/bn/co-586.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/bn/x86-mont.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/cpu-x86-asm.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/md5/md5-586.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/modes/ghash-x86.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/rc4/rc4-586.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/sha/sha1-586.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/sha/sha256-586.asm \
  $(MY_LOCAL_PATH)/win-x86/crypto/sha/sha512-586.asm \

win_x86_64_sources := \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/aes/aes-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/aes/aesni-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/aes/bsaes-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/aes/vpaes-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/bn/rsaz-avx2.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/bn/rsaz-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/bn/x86_64-mont.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/bn/x86_64-mont5.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/cpu-x86_64-asm.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/md5/md5-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/modes/aesni-gcm-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/modes/ghash-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/rand/rdrand-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/rc4/rc4-md5-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/rc4/rc4-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/sha/sha1-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/sha/sha256-x86_64.asm \
  $(MY_LOCAL_PATH)/win-x86_64/crypto/sha/sha512-x86_64.asm \

